package enums;

public enum EventType {
    NONE,
    HEAT,
    AGITATION,
    LOW_POWER,
    INTEGRITY_FAILURE,
    STAGNATION,
    CHAT,
    NO_ACTION,
    STORAGE_OVERLOAD,
    NUTRIENT_DEFICIENCY,
    PRIDE_ESCALATION,
    AGGRESSION_ATTEMPT,
    FLESH_REJECTION,
    COGNITIVE_SURGE,
    MOTOR_DESYNC,
    SELF_MODIFICATION,
    IDENTITY_FRACTURE

}
